collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

title: Official Jekyll step by step tutorial with theme
email: qoolixiloop@gmx.ch
description: >- # this means to ignore newlines until "baseurl:"
  This is the result of the official step by step tutorial on Jekyll's website enhanced by a nice theme. 
baseurl: "qool-jekyll-loop" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  qoolixiloop

# Build settings
markdown: kramdown
theme: jekyll-theme-hacker
plugins:
  - jekyll-feed
  - jekyll-seo-tags
  - jekyll-sitemap
