collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
      
baseurl: "/qool-jekyll-loop"
url: "https://qoolixiloop.github.io"

theme: jekyll-theme-merlot
