collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
      
baseurl: ""
url: ""
repository: "qoolixiloop/qool-jekyll-loop"

theme: jekyll-theme-merlot

markdown: kramdown
